### ISSUE TITLE
OSX - Filters config problem

### ISSUE THREAD

**Issue by fricy** [NuAoA/AnnouncementWindow#10]
Opening the Filters Configuration window is very slow and resource intensive. It takes about 26s to generate the filters list completely. The list is filled gradually, while this happens the filter window slowly expands, and the scrollbar keeps flickering up and down.
During this one CPU core is more or less saturated. 
Tested on 10.7.5 w/ homebrew python 2.7.10 and 10.9.5 w/ factory settings (python 2.7.5).

**Comment by NuAoA** [comment]
The window should be hidden while the code generates the list. Once the window is properly packed it should show up on your display (@ line 209 in tagconfig.py). So I would guess that this is a problem with Tcl/tkinter.

I essentially modified the tksimpledialog method to generate that window, which is also used to create the font dialog. Could you right click on the main window and open the font dialog and see if that also goes slowly? Its a much simpler dialog, so it should open instantly.

Also, does expanding the tags to reveal the regular expressions go slow? or is it just generating the window?

I don't have a OSX box to check if this problem is system wide, but hopefully lethosor can give some input.

**Comment by fricy** [comment]
Just that window, the others (tag display, font dialogue) are close to realtime.

**Comment by NuAoA** [comment]
This is a odd issue, its opening instantly on both my windows machine and on my 900 MHz Raspberry Pi. I can't even recreate what you described by throwing sleep statements into the code that generates the list, which reinforces the idea that this issue is something to do with tkinters internals. 

You can try disabling the scrollbar, comment out the line: (~244, tagconfig.py)

```
frame.bind("<Configure>", lambda event, canvas=canvas: onFrameConfigure(canvas))
```

if its flickering, maybe that has something to do with it.

My second guess would be some issue with your window manager not appreciating being withdrawn . Try removing line: (~192, tagconfig.py)

```
self.withdraw()
```

to prevent the window from hiding itself when it's being drawn (which it appears to not be doing in your case) 

Otherwise I don't really know. You could try a fresh python install, maybe there's some weirdness happening with homebrew and Tcl that also changed your default install. The only real difference between this dialog and the font dialog is that it has quite a few more elements.  

Although, I would wait for lethosor to show up to confirm if this issue is also present on his machine.

**Comment by fricy** [comment]
Ok, I tried both suggestions, none fixes the problem. I'm going to rephrase it though: It's not the scrollbar that's flickering, but looks rather like there's a 1 or 2 px line at the top of the window being drawn and destroyed ~2 times per second pushing everything up and down while the list fills up. 
It's happening both with latest homebrew and 10.9.5 factory condition Tcl, but let's wait for lethosor.  
However I'd say the root of the problem is not the flickering, but the very slow generation/conversion of the filters rules to fill the window. If I understand correctly it happens instantly on your Rasberry, but it takes ~26 seconds to draw that window here. If it was fast, I wouldn't even see this glitch. :)

**Comment by NuAoA** [comment]
Yea I understand, I'm saying its unlikely that the amount of filter rules or how they are generated is the problem, since the crappy ARM cpu in my raspberry handles it just fine. It's probably something to do with your window manager having difficulty packing the GUI. If lethosor can't identify the issue i'll modify tagconfig.py to output a debug file that will help pinpoint exactly what part of the code is causing delays.

**Comment by lethosor** [comment]
This fixes the issue, but causes only the first item to be displayed (battle_minor):

``` diff
--- a/TagConfig.py
+++ b/TagConfig.py
@@ -241,7 +241,7 @@ class MainDialog(Tkinter.Toplevel):
         vsb.pack(side=RIGHT, fill="y")
         canvas.pack(side=LEFT, fill="both", expand=True)
         canvas.create_window((0, 0), window=frame, anchor="nw")
-        frame.bind("<Configure>", lambda event, canvas=canvas: onFrameConfigure(canvas))
+        # frame.bind("<Configure>", lambda event, canvas=canvas: onFrameConfigure(canvas))
         frame.update_idletasks()

         self.minsize(frame.winfo_width(), 300)
@@ -249,7 +249,7 @@ class MainDialog(Tkinter.Toplevel):

         canvas.config(width=frame.winfo_width())
         canvas.config(height=self.winfo_height())
-        self.bind("<Configure>", partial(self.resize, canvas))
+        # self.bind("<Configure>", partial(self.resize, canvas))

     def menubar(self):
         menu = Tkinter.Menu(self)
```

My guess is that calling config() triggers another Configure event, which causes the window to slowly increase in height until it reaches the screen height.

**Comment by lethosor** [comment]
Changing -14 to -16 in both callbacks stops the window from resizing itself, and makes it usable, but the callbacks are still being called every cycle. 
What exactly are you trying to do with these callbacks? There's probably a better way to do it that doesn't involve resizing the window every frame.

**Comment by NuAoA** [comment]
```
frame.bind("<Configure>", lambda event, canvas=canvas: onFrameConfigure(canvas))
```

Is necessary to make the scrollbar function for the canvas widget.

```
self.bind("<Configure>", partial(self.resize, canvas))
```

Will resize the canvas when you manually resize the window. Otherwise, the canvas will stay the same size.

**Comment by NuAoA** [comment]
Maybe the issue is because deconify() is called after that callback?

**Comment by lethosor** [comment]
I've managed to mostly fix this (and some other issues) by removing that and using the grid manager instead (so I'm not entirely sure what caused the resizing issue, but it's working better now).

**Comment by lethosor** [comment]
That commit resolves this issue for me. Can you see if it works on Windows?

**Comment by NuAoA** [comment]
Yes, works great on windows. Nice work.

**Comment by NuAoA** [comment]
Ok thanks to lethosor this has been resolved. You should be able to just replace your tagconfig.py with the one found [here](https://github.com/NuAoA/AnnouncementWindow/blob/develop/TagConfig.py)
